### ISSUE TITLE
Last error occurred not populated by stream_socket_enable_crypto

### ISSUE THREAD

**Issue by zaerl** [WordPress/php-toolkit#120]
The PHP last error is not guaranteed to be populated by`stream_socket_enable_crypto`, so it can be `null` here https://github.com/WordPress/blueprints-library/blob/trunk/src/WordPress/AsyncHttp/Client.php#L491 if the function fails.

Should be changed to:

```php
$report = error_get_last();
$this->set_error( $request, new HttpError( 'Failed to enable crypto: ' . ( is_array( $report ) ? $report['message'] : 'unknown' ) ) );
```

**Comment by adamziel** [comment]
Oh, good catch! Would you like to start a PR for that?
