### ISSUE TITLE
Concurrent resource resolution flow

### ISSUE THREAD

**Issue by adamziel** [WordPress/php-toolkit#8]
Blueprints reference files using [Resource declarations](https://wordpress.github.io/wordpress-playground/blueprints-api/resources). Let's build a PHP resource resolver that can support:

* Concurrent resolution (async downloads [are already implemented](https://github.com/WordPress/blueprints/blob/18c8d0a43d28bb4e456d2ca7aaa49179a98129fd/setup_wordpress.php)!)
* Concurrency limits, e.g. at most 10 requests at once
* Different data sources (local files, URLs, string buffers)
* Streams as the primary data processing primitive
* Reporting progress (total and per resource)

Here's what the usage could look like:

```php
<?php

$res = new ResourceManager();
$res->events->addListener('progress', function($details) use($ui) {
    // Update the UI as we receive more data
    $ui->setFileProgress($details->resourceIdentifier, $details->progress);
});

$fp1 = $res->resolve("https://wordpress.org/gutenberg.zip");
// ... start 11 more requests, but only 10 will be active at the same time ...

// Reading from files could have a separate concurrency limit
$fp12 = $res->resolve("./plugin.zip");

// The, as we execute steps, they would do something like this:

class UnzipStep {
    public function execute($args) {
        // $args->zipFile is a regular PHP resource and extract_zip_file() does fread().
        // If the underlying download didn't start yet, fread() should block and wait for the data.
        extract_zip_file($args->zipFile, $args->toPath);
    }
}

fclose($fp1);
```

CC @bgrgicak

**Comment by bgrgicak** [comment]
@adamziel how I understand this is.

We need to add a queue (or multiple) that will allow us to start resolving resources. The queue will use ContainerBuilder to run. It's main goal is to limit the amount of concurrent requests (different limits for request types).

**Comment by adamziel** [comment]
> We need to add a queue (or multiple) that will allow us to start resolving resources.
> It's main goal is to limit the amount of concurrent requests (different limits for request types).

@bgrgicak exactly!

> The queue will use ContainerBuilder to run.

ContainerBuilder isn't related to the queues, it's just a tool to construct class instances. Technically, it creates a [Pimple](https://github.com/silexphp/Pimple) (Dependency Injection Container) instance and defines services.

Let's say the queue will be a class called `ResourceQueue`. I'd like to use it in this MVP compilation flow instead of `$resourceMap`:

https://github.com/WordPress/blueprints/blob/b03fa1a57ab2cbf1fe831ee72de76691d218f6a7/blueprint_compiling.php#L95-L107

Here's what it could look like:

```php
 $queue = new ResourceQueue(); 
 foreach ( $resources as $resourceDeclaration ) {
 	$queue->enqueue( $resourceDeclaration );
 }
```

Then, the `StepHandlers` would call `$this->queue->getStream( $input->file );` similarly to what this `WriteFileHandler` does:

https://github.com/WordPress/blueprints/blob/b03fa1a57ab2cbf1fe831ee72de76691d218f6a7/src/WordPress/Blueprints/Steps/WriteFileHandler.php#L10-L20

This way resources could start to pre-fetch before the first step, which is required for speed, and then each executed step would block until the required resource streams are available, which is required for consistency. What do you think?

**Comment by bgrgicak** [comment]
Sounds good to me! I will get back to working on it this week after I finish the logger (probably Tuesday).

**Comment by adamziel** [comment]
Done in https://github.com/WordPress/blueprints-library/pull/72
