### ISSUE TITLE
Import WXR using WP-CLI

### ISSUE THREAD

**Issue by adamziel** [WordPress/php-toolkit#90]
In blueprints v1, the `importFile` step runs `fetch()` requests to simulate a user going through the importer flow.

* It won't work with the PHP library as there's no `fetch()`
* It's difficult to extract error information
* It's prone to `/wp-admin` redirects

See [this issue](https://github.com/WordPress/wordpress-playground/issues/1124) for more context.

In V2, let's lean on WP-CLI and this command: https://github.com/wp-cli/import-command

**Comment by Mte90** [comment]
Any ETA for this?
Now the wp plugin repo has the option to turn on the live preview

**Comment by flexseth** [comment]
> Any ETA for this?
> 
> Now the wp plugin repo has the option to turn on the live preview 

The existing spec is in documentation process - v1

V2 is in the works but will probably be a bit until the main project is tooled accordingly. 

We're looking at focusing on the developer experience and hoping devs can build out examples that will help the greater community!

**Comment by adamziel** [comment]
@Mte90 I think https://github.com/WordPress/wordpress-playground/issues/1183 solved it without WP-CLI!

I just tried this Blueprint and it imported Glossary entries:

```json
{
  "landingPage": "/wp-admin/post.php?post=9&action=edit",
  "phpExtensionBundles": [
    "kitchen-sink"
  ],
  "steps": [
    {
      "step": "login"
    },
    {
      "step": "installPlugin",
      "pluginZipFile": {
        "resource": "wordpress.org/plugins",
        "slug": "glossary-by-codeat"
      },
      "options": {
        "activate": true
      }
    },
    {
      "step": "importFile",
      "file": {
        "resource": "url",
        "url": "https://docs.codeat.co/glossary/playground-import.xml"
      }
    }
  ]
}
```
